### ISSUE TITLE
nonuniform discrete Fourier transform of type II

### ISSUE THREAD

**Issue by kylematoba** [mmuckley/torchkbnufft#68]
If I read 

https://en.wikipedia.org/wiki/Non-uniform_discrete_Fourier_transform#Definition

correctly, then "adjoint nonuniform DFT" (also called "nonuniform discrete Fourier transform of type II") would entail interpolating in space. 

Thus, I expect that `KbNufftAdjoint` would not operate in frequency space, as seems to be suggested by the docs. Is there a standard reduction in this field that allows me to interpolate in space using this logic please?

**Comment by mmuckley** [comment]
Hello @kylematoba, in our case we define a forward NUFFT as a linear operator that applies an FFT followed by a linear interpolation with a Kaiser-Bessel function. Since it is a linear operator, the adjoint is defined as the adjoint of these individual operations in reverse order.

I think what you are describing would be some sort of Non-uniform inverse fast Fourier Transform (NUIFFT) operator, which would have its own distinct adjoint separate from any implemented in this package.

**Comment by apt-get-nat** [comment]
So, do I understand correctly that there is no way to use your package to perform a Fourier transform with data that is nonuniform in space to modes that are uniform in frequency?

**Comment by mmuckley** [comment]
@apt-get-nat using the duality property you may be able to approximate this operation using the package.

**Comment by mmuckley** [comment]
Closing as this does not document a bug.
